'use strict';function _toConsumableArray(a){return _arrayWithoutHoles(a)||_iterableToArray(a)||_nonIterableSpread()}function _arrayWithoutHoles(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}}function _iterableToArray(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance")}// # use golden ratio
var golden_ratio_conjugate=.618033988749895,h=.333,generateBestHue=function(){h+=golden_ratio_conjugate,h%=1;var a=Math.floor(360*h);return a},colorMapCache={},getColor=function(a,b){var c=colorMapCache[a];//console.log("getColor", { value, pos, hue });
return void 0===c&&(c=generateBestHue(),colorMapCache[a]=c),"hsl(".concat(c,", 70%, ").concat(45+20*b,"%)")},getTimeStamp=function(){/*
  getHours() - Returns the hour of the day (0-23).
  getMinutes() - Returns the minute (0-59).
  getSeconds() - Returns the second (0-59).
  getMilliseconds() - Returns the milliseconds (0-999).
  */var a=new Date;return"".concat(a.getHours().toString().padStart(2,"0"),":").concat(a.getMinutes().toString().padStart(2,"0"),":").concat(a.getSeconds().toString().padStart(2,"0"),".").concat(a.getMilliseconds())},globalConfig={disabled:!1,disableInProduction:!0},transports=[],registerTransport=function(a){globalConfig.disabled||globalConfig.disableInProduction&&process&&process.env&&!1||!a.isAvailableInEnvironment(globalConfig)||(a.initialise(),transports.push(a))},transformArgs=function(a){return function(){for(var b=arguments.length,c=Array(b),d=0;d<b;d++)c[d]=arguments[d];return void 0===a?c:a.smile?[":)"].concat(c):a.timestamp?[getTimeStamp()].concat(c):c;// untouched
}},dispatchToTransports=function(a,b){return function(){for(var c=arguments.length,d=Array(c),e=0;e<c;e++)d[e]=arguments[e];// this is essentially compose()
transports.map(function(c){return c.dispatch(a,b).apply(void 0,_toConsumableArray(transformArgs(b).apply(void 0,d)))})}},levels=["log","debug","error","warn","fatal"],outputs=function(a){return{log:function(){return dispatchToTransports("log",a).apply(void 0,arguments)},debug:function(){return dispatchToTransports("debug",a).apply(void 0,arguments)},error:function(){return dispatchToTransports("error",a).apply(void 0,arguments)},warn:function(){return dispatchToTransports("warn",a).apply(void 0,arguments)}}},lgr=function(a){return outputs(a)};//let h = Math.random(); // # use random start value
levels.map(function(a){return lgr[a]=function(){var b;return(b=outputs())[a].apply(b,arguments)}});var makeLogStyle=function(){var a=0<arguments.length&&arguments[0]!==void 0?arguments[0]:{},b=a.backgroundColor,c=void 0===b?null:b,d=a.color,e=void 0===d?"white":d,f=1<arguments.length&&arguments[1]!==void 0?arguments[1]:"",g=2<arguments.length&&arguments[2]!==void 0?arguments[2]:0,h=null===c?getColor(f,g):c;return"background-color:".concat(h,";color:").concat(e,";border-radius:3px;padding:2px 4px;margin-left:2px;font-size:").concat("$1.5rem",";font-weight:").concat(0===g?"bold":"normal")},transformConsoleArgs=function(a){return function(){for(var b=arguments.length,c=Array(b),d=0;d<b;d++)c[d]=arguments[d];if(a===void 0)return c;if(a.meta){var e="string"==typeof a.meta?["%c".concat(a.meta),makeLogStyle(a,a.meta)]:[a.meta.map(function(a){return"%c".concat(a)}).join("")].concat(_toConsumableArray(a.meta.map(function(b,c){return makeLogStyle(a,a.meta[0],c)})));//console.log("ARGDEBUG", [...metaArgs, ...args]);
return[].concat(_toConsumableArray(e),c)}return c}},isAvailableInEnvironment=function(){return console!==void 0},dispatch=function(a,b){return function(){var c;(c=console)[a].apply(c,_toConsumableArray(transformConsoleArgs(b).apply(void 0,arguments)))}},initialise=function(){},consoleTransport={isAvailableInEnvironment:isAvailableInEnvironment,dispatch:dispatch,initialise:initialise},writerOutputEl=null,makeLogStyle$1=function(){var a=0<arguments.length&&arguments[0]!==void 0?arguments[0]:{},b=a.backgroundColor,c=void 0===b?null:b,d=a.color,e=void 0===d?"white":d,f=1<arguments.length&&arguments[1]!==void 0?arguments[1]:"",g=2<arguments.length&&arguments[2]!==void 0?arguments[2]:0,h=null===c?getColor(f,g):c;return"display:inline-block;background-color:".concat(h,";color:").concat(e,";border-radius:3px;padding:2px 4px;margin-left:2px;")},transformConsoleArgs$1=function(a){return function(){for(var b=arguments.length,c=Array(b),d=0;d<b;d++)c[d]=arguments[d];if(a===void 0)return c;if(a.meta){var e="string"==typeof a.meta?"<div style=\"".concat(makeLogStyle$1(a,a.meta),"\">").concat(a.meta,"</div>"):a.meta.map(function(b,c){return"<div style=\"".concat(makeLogStyle$1(a,a.meta[0],c),"\">").concat(b,"</div>")}).join("");//console.log("ARGDEBUG", [...metaArgs, ...args]);
return[e].concat(c).join(" ")}return c}},lineStyles={log:"",debug:"color:blue",error:"color:red",warn:"color:orange"},isAvailableInEnvironment$1=function(){return window!==void 0&&window.document!==void 0},makeStyle=function(a){return Object.keys(a).map(function(b){return"".concat(b,":").concat(a[b])}).join(";")},makeEl=function a(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{},c=b.tag,d=b.style,e=b.attrs,f=b.html,g=b.children,h=b.refOut,i=b.events,j=document.createElement(c);if(f&&(j.innerHTML=f),d){var k=makeStyle(d);j.setAttribute("style",k)}if(h&&h(j),e)for(var l in e){var m=e[l];j.setAttribute(l,m)}if(i)for(var n in i)j.addEventListener(n,i[n]);return g&&g.map(function(b){j.appendChild(a(b))}),j},initialise$1=function(){var a=document.getElementById("lgr_html_dom_writer__");// don't remount
if(!a){//writerOutputEl;
var b=makeEl({tag:"DIV",// WRAPPER
attrs:{id:"lgr_html_dom_writer__",draggable:"draggable"},style:{display:"flex","flex-direction":"column",position:"fixed",width:"400px",top:"300px","background-color":"rgba(255,255,255,0.9)",bottom:"0px",right:"0px",overflow:"hidden",border:"solid 1px #007fe0","font-size":"12px","font-family":"Helvetica, arial"},children:[{tag:"DIV",// HEADER
style:{color:"white",display:"flex","flex-direction":"row","background-color":"#007fe0",padding:"10px","font-size":"12px"},children:[{tag:"DIV",html:"lgr",style:{"flex-grow":"2"}},{tag:"DIV",html:"&#0149;",style:{"align-self":"flex-end","font-size":"20px","line-height":"0.5pt",height:"14px","letter-spacing":"0.5pt"},events:{click:function(){writerOutputEl.innerHTML="ACCESS"}}}]},{tag:"DIV",// CONTENT
refOut:function(a){writerOutputEl=a},style:{"flex-grow":2,padding:"10px",overflow:"scroll"}}]});//console.log("wrapper", wrapper);
document.body.appendChild(b)}},dispatch$1=function(a,b){return function(){var c=document.createElement("DIV");c.setAttribute("style","margin-bottom:2px;".concat(lineStyles[a])),c.innerHTML=transformConsoleArgs$1(b).apply(void 0,arguments),writerOutputEl.append(c)}},htmlDomTransport={isAvailableInEnvironment:isAvailableInEnvironment$1,dispatch:dispatch$1,initialise:initialise$1},lgrBrowser=function(){return registerTransport(consoleTransport),lgr},demoObj={a:"objects",b:"work",c:"too",success:!0,someNumber:123},lgr$1=lgrBrowser();registerTransport(htmlDomTransport),lgr$1.log("hello"),lgr$1.debug("world"),lgr$1.error("uh oh"),lgr$1.log(demoObj),lgr$1({smile:!0}).debug("pass log config!"),lgr$1({timestamp:!0}).debug("pass log config!");var myLogger=lgr$1({meta:"somelogger",timestamp:!0});myLogger.debug("magic"),myLogger.debug("log"),myLogger.debug("formatting!"),myLogger.debug(demoObj);var colorLogger=lgr$1({meta:["colors!","red ..."],backgroundColor:"#FF0000"});colorLogger.debug("color"),colorLogger.debug("me"),colorLogger.debug("happy"),colorLogger.debug(demoObj),lgr$1({meta:["a","colors"]}).log("random"),lgr$1({meta:["b","colors"]}).log("colors"),lgr$1({meta:["c","colors"]}).log("each"),lgr$1({meta:["d","colors"]}).log("time");
